sudo: required
services:
  - docker


before_install:
  - docker build -t beuelvinc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=TRUE beuelvinc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"  # take from url
  app: "docker" # same as in aws
  env: "Docker-env" #same as in aws
  bucket_name: "elasticbeanstalk-us-east-1-250932413033" # same as in aws
  bucket_path: "docker" # changes after u deploy
  on:
    branch: master #main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
